analytics_copilot:
  target: dev

  outputs:
    dev:
      type: databricks

      catalog: <SEU_CATALOG>

      schema: analytics

      host: <SEU_HOST_DATABRICKS>

      http_path: <SEU_HTTP_PATH>

      token: "{{ env_var('DATABRICKS_TOKEN') }}"

      threads: 4